apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg
spec:
  selector:
    matchLabels:
      app: pg
  template:
    metadata:
      labels:
        app: pg
    spec:
      containers:
      - name: pg
        image: postgres:13
        env:
        - name: POSTGRES_PASSWORD
          value: "123456"
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: disco-pg
